import V7.Foundation
import Mathlib.MeasureTheory.Integral.Lebesgue.Basic

open MeasureTheory

namespace V7

abbrev StrictPoint := Point 1
abbrev StrictObservation := Observation 1
abbrev StrictTranscript := List StrictObservation

/-- Natural Borel structure on one exact value-gradient observation. -/
instance : MeasurableSpace StrictObservation :=
  MeasurableSpace.comap
    (fun obs => (obs.point, obs.value, obs.gradient)) inferInstance

/-- Cylinder sigma algebra on finite exact-pair transcripts, generated by
length events and Borel events at each finite coordinate. -/
@[instance_reducible] def strictTranscriptMeasurableSpace :
    MeasurableSpace StrictTranscript :=
  MeasurableSpace.generateFrom {s : Set StrictTranscript |
    (∃ n : ℕ, s = {trace | trace.length = n}) ∨
    ∃ (k : ℕ) (B : Set StrictObservation), MeasurableSet B ∧
      s = {trace | ∃ obs ∈ B, (trace.drop k).head? = some obs}}

instance : MeasurableSpace StrictTranscript := strictTranscriptMeasurableSpace

/-- A deterministic strict-local method sees only the supplied accuracy,
initial point, and its finite exact-pair transcript. -/
structure StrictLocalMethod where
  eps : ℝ
  x0 : StrictPoint
  nextQuery : StrictTranscript → StrictPoint
  output : ℕ → StrictTranscript → StrictPoint
  nextQuery_measurable : Measurable nextQuery
  output_measurable : ∀ N, Measurable (output N)

/-- A randomized strict method is a measurable seed-indexed family of strict
methods.  The adversarial instance is quantified after this whole family,
not separately for each seed. -/
structure RandomizedStrictLocalMethod (Ω : Type*) [MeasurableSpace Ω] where
  run : Ω → StrictLocalMethod
  joint_nextQuery_measurable : Measurable
    (fun z : Ω × StrictTranscript => (run z.1).nextQuery z.2)
  joint_output_measurable : ∀ N, Measurable
    (fun z : Ω × StrictTranscript => (run z.1).output N z.2)

instance [MeasurableSpace Ω] : CoeFun (RandomizedStrictLocalMethod Ω)
    (fun _ => Ω → StrictLocalMethod) := ⟨RandomizedStrictLocalMethod.run⟩

def StrictTranscriptExact (oracle : PairOracle 1) (trace : StrictTranscript) : Prop :=
  TraceExact oracle trace

def StrictAllFirstNQueriesFail (eps : ℝ) (oracle : PairOracle 1)
    (trace : StrictTranscript) (N : ℕ) : Prop :=
  trace.length = N ∧
  ∀ obs ∈ trace, eps < |oracle.gradient obs.point 0|

def StrictFiniteOutputFails (method : StrictLocalMethod) (oracle : PairOracle 1)
    (trace : StrictTranscript) (N : ℕ) : Prop :=
  method.eps < |oracle.gradient (method.output N trace) 0|

def StrictSuccessThrough (method : StrictLocalMethod) (oracle : PairOracle 1)
    (trace : StrictTranscript) (N : ℕ) : Prop :=
  (∃ obs ∈ trace.take N, |oracle.gradient obs.point 0| ≤ method.eps) ∨
  |oracle.gradient (method.output N trace) 0| ≤ method.eps

def ExactGradientLipschitzConstant (oracle : PairOracle 1) (L : ℝ) : Prop :=
  (∀ x y, |oracle.gradient x 0 - oracle.gradient y 0| ≤ L * |x 0 - y 0|) ∧
  ∀ L' : ℝ,
    (∀ x y, |oracle.gradient x 0 - oracle.gradient y 0| ≤ L' * |x 0 - y 0|) →
    L ≤ L'

def IsCoerciveReal (f : StrictPoint → ℝ) : Prop :=
  ∀ B : ℝ, ∃ R : ℝ, 0 ≤ R ∧ ∀ x, R ≤ |x 0| → B ≤ f x

def UniqueMinimizer (f : StrictPoint → ℝ) (xstar : StrictPoint) : Prop :=
  (∀ x, f xstar ≤ f x) ∧ ∀ x, f x = f xstar → x = xstar

/-- The affine--quadratic--affine family from `thm:impossibility`. -/
noncomputable def strictHardFamily (eps : ℝ) (x0 : StrictPoint) (H : ℝ)
    (x : StrictPoint) : ℝ :=
  let g := 2 * eps
  let z := x 0 - x0 0
  if z ≤ H then -g * z
  else if z ≤ 3 * H then -g * z + (g / (2 * H)) * (z - H) ^ 2
  else g * z - 4 * g * H

noncomputable def strictHardDerivative (eps : ℝ) (x0 : StrictPoint) (H : ℝ)
    (x : StrictPoint) : StrictPoint :=
  fun _ =>
    let g := 2 * eps
    let z := x 0 - x0 0
    if z ≤ H then -g else if z ≤ 3 * H then g * (z / H - 2) else g

def StrictHardInstance (eps : ℝ) (x0 : StrictPoint) (H L R : ℝ)
    (oracle : PairOracle 1) (xstar : StrictPoint) : Prop :=
  0 < H ∧
  oracle.value = strictHardFamily eps x0 H ∧
  oracle.gradient = strictHardDerivative eps x0 H ∧
  O3.IsConvexObjective oracle.value ∧
  IsCoerciveReal oracle.value ∧
  O3.IsCoordinateGradient oracle.value oracle.gradient ∧
  UniqueMinimizer oracle.value xstar ∧
  ExactGradientLipschitzConstant oracle L ∧
  0 < L ∧ R = |xstar 0 - x0 0| ∧ L * R / eps = 4

noncomputable def strictAffineOracle (eps : ℝ) (x0 : StrictPoint) : PairOracle 1 :=
  { value := fun x => -(2 * eps) * (x 0 - x0 0)
    gradient := fun _ _ => -(2 * eps) }

def StrictNormalizedInstance (eps : ℝ) (x0 : StrictPoint) (L R : ℝ)
    (oracle : PairOracle 1) (xstar : StrictPoint) : Prop :=
  O3.IsConvexObjective oracle.value ∧ IsCoerciveReal oracle.value ∧
  O3.IsCoordinateGradient oracle.value oracle.gradient ∧
  UniqueMinimizer oracle.value xstar ∧
  ExactGradientLipschitzConstant oracle L ∧
  0 < L ∧ R = |xstar 0 - x0 0| ∧ L * R / eps = 4

/-- A source-level hitting-time carrier.  `top` means no queried or returned
small-gradient point is reached. -/
noncomputable def strictHittingTime (method : StrictLocalMethod)
    (oracle : PairOracle 1) (traces : ℕ → StrictTranscript) : ENNReal :=
  sInf {t : ENNReal | ∃ N : ℕ, t = (N : ENNReal) ∧
    StrictSuccessThrough method oracle (traces N) N}

def StrictRunConsistent (method : StrictLocalMethod) (oracle : PairOracle 1)
    (trace : StrictTranscript) : Prop :=
  StrictTranscriptExact oracle trace ∧
  ∀ (t : ℕ) (ht : t < trace.length),
    (trace.get ⟨t, ht⟩).point =
      if t = 0 then method.x0 else method.nextQuery (trace.take t)

end V7
