import V7.Proofs.Stage3BelowTwoS3F.Closure
import V7.Proofs.Stage4AboveTwoDualPhase.AnalyticPrefix
import V7.Proofs.Stage4AboveTwoFinalTrial.Proof

#check V7.normingDirection_correct
#check V7.anchor
#check V7.euclideanGap
#check V7.finiteDataOGMG
#check V7.euclideanTrial
#check V7.trialOutcomeCertification
#check V7.geometricTrialAmortization
#check V7.belowGeometry
#check V7.belowPrimal
#check V7.belowPointwiseResidualIdentity
#check V7.belowTerminalGradient
#check V7.belowGuardScaling
#check V7.belowTrial
#check V7.aboveGeometry
#check V7.aboveWeightErrorBalance
#check V7.abovePointwiseResidualIdentity
#check V7.abovePrimalTerminalGap
#check V7.aboveDualTerminalEnergy
#check V7.abovePhaseOneHorizonBound
#check V7.abovePhaseTwoTerminalGradientBound
#check V7.aboveTrial
